name = "my-jant-site"
main = "index.js"
compatibility_date = "2026-01-20"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./node_modules/@jant/core/dist/client"

[vars]
SITE_URL = ""

[[d1_databases]]
binding = "DB"
database_name = "my-site-db"
database_id = "local"
migrations_dir = "node_modules/@jant/core/src/db/migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "my-site-media"
