import { program } from "commander";
import * as p from "@clack/prompts";
import chalk from "chalk";
import crypto from "crypto";
import fs from "fs-extra";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// @jant/core version - injected at build time by prepublish script
const CORE_VERSION = "__JANT_CORE_VERSION__";

// Template directory resolution:
// - If template/ exists next to dist/ (after prepublish copy), use that
// - Otherwise, use the source templates/jant-site (for local dev)
// From dist/index.js: ../template or ../../../templates/jant-site
const TEMPLATE_DIR = fs.existsSync(path.resolve(__dirname, "../template"))
  ? path.resolve(__dirname, "../template")
  : path.resolve(__dirname, "../../../templates/jant-site");

interface ProjectConfig {
  projectName: string;
  targetDir: string;
  s3?: boolean;
}

/**
 * Validate project name
 */
function isValidProjectName(name: string): boolean {
  return /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(name);
}

/**
 * Sanitize project name into a valid slug
 */
function toValidProjectName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");
}

/**
 * Generate a secure random AUTH_SECRET (base64, 32 bytes = 44 chars)
 */
function generateAuthSecret(): string {
  return crypto.randomBytes(32).toString("base64");
}

/**
 * Copy template files to target directory
 */
async function copyTemplate(config: ProjectConfig): Promise<void> {
  const { projectName, targetDir } = config;

  // Copy all template files
  await fs.copy(TEMPLATE_DIR, targetDir, {
    filter: (src) => {
      const basename = path.basename(src);
      // Skip system files and development artifacts
      if (basename.startsWith(".DS_Store")) return false;
      if (basename === "node_modules") return false;
      if (basename === ".wrangler") return false;
      if (basename === ".swc") return false;
      if (basename === ".dev.vars") return false;
      if (basename === "pnpm-lock.yaml") return false;
      if (basename === "dist") return false;
      if (basename === "wrangler.demo.toml") return false;
      if (basename === "reset-demo.sql") return false;
      if (basename === "seed-demo.sql") return false;
      if (basename === "reset-local.sql") return false;
      if (basename === "seed-local.sql") return false;
      if (basename === "export-demo.mjs") return false;
      return true;
    },
  });

  // Determine secrets file names based on deployment target
  // Cloudflare Workers: .dev.vars.example / .dev.vars
  // Future VPS/Docker: .env.example / .env
  const secretsExampleFile = ".dev.vars.example";
  const secretsFile = ".dev.vars";

  // Rename special files/directories (prefixed with _ to avoid issues)
  const renames: Array<[string, string]> = [
    ["_gitignore", ".gitignore"],
    ["_env.example", secretsExampleFile],
    ["_github", ".github"],
  ];

  for (const [from, to] of renames) {
    const fromPath = path.join(targetDir, from);
    const toPath = path.join(targetDir, to);
    if (await fs.pathExists(fromPath)) {
      await fs.rename(fromPath, toPath);
    }
  }

  // Update package.json with project name and fix dependencies
  const pkgPath = path.join(targetDir, "package.json");
  if (await fs.pathExists(pkgPath)) {
    const pkg = await fs.readJson(pkgPath);
    pkg.name = projectName;
    // Replace workspace:* with version injected at build time
    if (pkg.dependencies?.["@jant/core"] === "workspace:*") {
      pkg.dependencies["@jant/core"] = `^${CORE_VERSION}`;
    }
    await fs.writeJson(pkgPath, pkg, { spaces: 2 });
  }

  // Update wrangler.toml: process @create-jant markers
  const wranglerPath = path.join(targetDir, "wrangler.toml");
  if (await fs.pathExists(wranglerPath)) {
    let content = await fs.readFile(wranglerPath, "utf-8");
    const vars: Record<string, string> = { name: projectName };

    // Replace value markers: `name = "jant-site" # @create-jant: "${name}"` → `name = "my-project"`
    content = content.replace(
      /^(.+=\s*)"[^"]*"\s*#\s*@create-jant:\s*"([^"]*)"/gm,
      (_, prefix: string, template: string) => {
        const value = template.replace(
          /\$\{(\w+)\}/g,
          (__, key: string) => vars[key] ?? "",
        );
        return `${prefix}"${value}"`;
      },
    );

    // Remove lines marked with @create-jant: @remove (monorepo-only config)
    content = content.replace(/^.*#\s*@create-jant:\s*@remove\s*\n?/gm, "");

    await fs.writeFile(wranglerPath, content, "utf-8");
  }

  // Generate .dev.vars with a secure AUTH_SECRET
  const authSecret = generateAuthSecret();
  let devVarsContent = `# Generated by create-jant
# AUTH_SECRET is used for session encryption (better-auth)
AUTH_SECRET=${authSecret}
`;

  // S3 storage configuration
  if (config.s3) {
    // Uncomment S3 vars and set STORAGE_DRIVER in wrangler.toml
    if (await fs.pathExists(wranglerPath)) {
      let wContent = await fs.readFile(wranglerPath, "utf-8");
      // Uncomment STORAGE_DRIVER and S3 vars
      wContent = wContent.replace(
        /^# STORAGE_DRIVER = "s3"/m,
        'STORAGE_DRIVER = "s3"',
      );
      wContent = wContent.replace(/^# S3_ENDPOINT = /m, "S3_ENDPOINT = ");
      wContent = wContent.replace(/^# S3_BUCKET = /m, "S3_BUCKET = ");
      wContent = wContent.replace(/^# S3_REGION = /m, "S3_REGION = ");
      wContent = wContent.replace(/^# S3_PUBLIC_URL = /m, "S3_PUBLIC_URL = ");
      // Remove [[r2_buckets]] section
      wContent = wContent.replace(/\n\[\[r2_buckets\]\][^[]*/s, "\n");
      await fs.writeFile(wranglerPath, wContent, "utf-8");
    }

    // Add S3 secrets to .dev.vars
    devVarsContent += `
# S3-compatible storage credentials
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
`;
  }

  await fs.writeFile(
    path.join(targetDir, secretsFile),
    devVarsContent,
    "utf-8",
  );

  // Patch vite.config.ts for npm-installed @jant/core
  const viteConfigPath = path.join(targetDir, "vite.config.ts");
  if (await fs.pathExists(viteConfigPath)) {
    let content = await fs.readFile(viteConfigPath, "utf-8");
    // Remove monorepo-only blocks (marked with @monorepo-only-start/end)
    content = content.replace(
      /\s*\/\/ @monorepo-only-start[\s\S]*?\/\/ @monorepo-only-end\n?/g,
      "",
    );
    // Update lingui plugin paths: src/ -> dist/, .ts -> .js
    content = content.replace(
      /@jant\/core\/src\/([^"']+)\.ts/g,
      "@jant/core/dist/$1.js",
    );
    await fs.writeFile(viteConfigPath, content, "utf-8");
  }

  // Note: tsconfig.json is already merged during prepublishOnly (prepare-template script)
  // No runtime merging needed - the template/ directory contains a standalone tsconfig.json
}

/**
 * Main CLI function
 */
async function main(): Promise<void> {
  console.log(); // eslint-disable-line no-console
  p.intro(chalk.bgCyan.black(" create-jant "));

  program
    .name("create-jant")
    .description("Create a new Jant project")
    .argument("[project-name]", "Name of the project")
    .option("-y, --yes", "Skip prompts and use defaults")
    .option("--s3", "Use S3-compatible storage instead of Cloudflare R2")
    .parse();

  const args = program.args;
  const opts = program.opts<{ yes?: boolean; s3?: boolean }>();

  let projectName: string;

  // Get project name from argument or prompt
  if (args[0]) {
    projectName = args[0];
  } else if (opts.yes) {
    projectName = "jant-site";
  } else {
    const result = await p.text({
      message: "What is your project name?",
      placeholder: "jant-site",
      defaultValue: "jant-site",
      validate: (value) => {
        if (!value) return "Project name is required";
        const sanitized = toValidProjectName(value);
        if (!isValidProjectName(sanitized)) {
          return "Project name must be lowercase alphanumeric with hyphens";
        }
        return undefined;
      },
    });

    if (p.isCancel(result)) {
      p.cancel("Operation cancelled");
      process.exit(0);
    }

    projectName = result as string;
  }

  // Sanitize project name
  if (!isValidProjectName(projectName)) {
    const sanitized = toValidProjectName(projectName);
    p.log.warn(
      `Project name sanitized: ${chalk.yellow(projectName)} -> ${chalk.green(sanitized)}`,
    );
    projectName = sanitized;
  }

  const targetDir = path.resolve(process.cwd(), projectName);

  // Check if directory already exists
  if (await fs.pathExists(targetDir)) {
    const files = await fs.readdir(targetDir);
    if (files.length > 0) {
      if (opts.yes) {
        p.log.error(
          `Directory ${chalk.red(projectName)} already exists and is not empty`,
        );
        process.exit(1);
      }

      const overwrite = await p.confirm({
        message: `Directory ${chalk.yellow(projectName)} already exists and is not empty. Overwrite?`,
        initialValue: false,
      });

      if (p.isCancel(overwrite) || !overwrite) {
        p.cancel("Operation cancelled");
        process.exit(0);
      }

      await fs.emptyDir(targetDir);
    }
  }

  const config: ProjectConfig = {
    projectName,
    targetDir,
    s3: opts.s3,
  };

  const spinner = p.spinner();
  spinner.start("Creating project...");

  try {
    await copyTemplate(config);
    spinner.stop("Project created successfully!");
  } catch (error) {
    spinner.stop("Failed to create project");
    p.log.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }

  // Show next steps
  console.log(); // eslint-disable-line no-console
  p.note(
    [`cd ${projectName}`, "pnpm install", "pnpm dev"].join("\n"),
    "Next steps",
  );

  p.outro(chalk.green("Happy coding!"));
}

main().catch((error) => {
  console.error(chalk.red("Error:"), error); // eslint-disable-line no-console
  process.exit(1);
});
