UPDATE "site_setting"
SET "value" = CASE "value"
  WHEN 'International Date Line West' THEN 'Etc/GMT+12'
  WHEN 'American Samoa' THEN 'Pacific/Pago_Pago'
  WHEN 'Hawaii' THEN 'Pacific/Honolulu'
  WHEN 'Alaska' THEN 'America/Anchorage'
  WHEN 'Pacific Time (US & Canada)' THEN 'America/Los_Angeles'
  WHEN 'Mountain Time (US & Canada)' THEN 'America/Denver'
  WHEN 'Central Time (US & Canada)' THEN 'America/Chicago'
  WHEN 'Eastern Time (US & Canada)' THEN 'America/New_York'
  WHEN 'Atlantic Time (Canada)' THEN 'America/Halifax'
  WHEN 'Newfoundland' THEN 'America/St_Johns'
  WHEN 'Buenos Aires' THEN 'America/Argentina/Buenos_Aires'
  WHEN 'Mid-Atlantic' THEN 'Atlantic/South_Georgia'
  WHEN 'Azores' THEN 'Atlantic/Azores'
  WHEN 'London' THEN 'Europe/London'
  WHEN 'Central European Time' THEN 'Europe/Paris'
  WHEN 'Eastern European Time' THEN 'Europe/Helsinki'
  WHEN 'Moscow' THEN 'Europe/Moscow'
  WHEN 'Tehran' THEN 'Asia/Tehran'
  WHEN 'Dubai' THEN 'Asia/Dubai'
  WHEN 'Kabul' THEN 'Asia/Kabul'
  WHEN 'Karachi' THEN 'Asia/Karachi'
  WHEN 'Mumbai' THEN 'Asia/Kolkata'
  WHEN 'Kathmandu' THEN 'Asia/Kathmandu'
  WHEN 'Dhaka' THEN 'Asia/Dhaka'
  WHEN 'Yangon' THEN 'Asia/Yangon'
  WHEN 'Bangkok' THEN 'Asia/Bangkok'
  WHEN 'Beijing' THEN 'Asia/Shanghai'
  WHEN 'Tokyo' THEN 'Asia/Tokyo'
  WHEN 'Adelaide' THEN 'Australia/Adelaide'
  WHEN 'Sydney' THEN 'Australia/Sydney'
  WHEN 'Noumea' THEN 'Pacific/Noumea'
  WHEN 'Auckland' THEN 'Pacific/Auckland'
  WHEN 'Nuku''alofa' THEN 'Pacific/Tongatapu'
  ELSE "value"
END
WHERE "key" = 'TIME_ZONE';
