-- Jant database export
-- Exported: 2026-03-21T14:45:57.149Z
-- Source: d1-remote

-- setting
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('HEADER_NAV_MAX_VISIBLE', '', 1774104129);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('HOME_DEFAULT_VIEW', '', 1774104129);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('NOINDEX', '', 1774104129);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('SHOW_JANT_BRANDING_ON_HOME', 'true', 1774104129);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('SITE_AVATAR', 'media/med_01km8dhfjafq895qcp3myds3fr.png', 1774104133);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('SITE_DESCRIPTION', 'Thoughts, links, and quotes — one post at a time', 1774104129);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('SITE_FAVICON_APPLE_TOUCH', 'site/apple-touch-icon.png', 1774104133);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('SITE_FAVICON_ICO', 'AAABAAIAEBAAAAEAIADbAAAAJgAAACAgAAABACAApQEAAAEBAACJUE5HDQoaCgAAAA1JSERSAAAAEAAAABAIBgAAAB/z/2EAAACQSURBVHgB7JJbDkYwEIX7d1m/F7bB+tgGL2yLfOUkTC94JznpzJyLpq13x/dv6/UNDpsLARg1eLrK41VY49yPl5HtIfGGHdCkgElI8cyyAVXXOIAInGt6IRsgwd36Bbj9IeUOiiuEy90AXHSImAQEd4gC7N9sbwOjAASYBPoS/DJMv5KgxOENO6AoCVOcPBsAAAD//+8rHvsAAAAGSURBVAMATYVBBaHquC4AAAAASUVORK5CYIKJUE5HDQoaCgAAAA1JSERSAAAAIAAAACAIBgAAAHN6evQAAAFaSURBVHgB7FU7TgMxEHW2RnAOKkS7aTYSFSE1krkAEjUFEjegoaDhAKSHQApSJCmySpkbbfysTDQ7ykr+bedIEz+PZ957nmJdKPEb6uqn1FXTRxjuhZBTLQMQbZSayKJUe8N9Aw3OdzQgD3hRasy1rAGeSC3WxUeaRalHf11FfedLXc3MBJpbH6HN11JRyL7ry6vOM1l72N8ZAwcYsMCIHt/bTuCP13eLff68DQwfRi3+J/1ob82TsoafSextAAQQQADzeH57UafyvEbiIAOShPb1bkvQeU1qwFmVFWYDeQJ5AnkCeQLeE5h/ftvXD88v+6IGQycDEKO4ODs/Keb7ChKJkwEq7mNNYiD09riQk4EuAeQRIAoNJwMgh5AM5GPDGGjmsSQR/b9FPV2PIwiiWuvpamImoJQBgyimgGbStAbQTwngvoNrHQ1AFAdmFDPgVNHmGfxDg+f2AAAA//8qMpNmAAAABklEQVQDAFPdhnjZjKuCAAAAAElFTkSuQmCC', 1774104133);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('SITE_FAVICON_VERSION', '202603211442', 1774104133);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('SITE_FOOTER', '', 1774104129);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('SITE_LANGUAGE', 'en', 1774104129);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('SITE_NAME', 'Jant', 1774104129);
INSERT INTO "setting" ("key", "value", "updated_at") VALUES('TIME_ZONE', 'Asia/Shanghai', 1774104072);

-- collection
INSERT INTO "collection" ("id", "title", "description", "sort_order", "created_at", "updated_at") VALUES('col_01km8dhgf6fq895qcxxsd51c5k', 'City Walks', 'Routes, corners, and small things I notice outside.', 'newest', 1774104134, 1774104134);
INSERT INTO "collection" ("id", "title", "description", "sort_order", "created_at", "updated_at") VALUES('col_01km8dhgrafqeakqanyeweejgq', 'Home Cooking', 'Weeknight dinners, soup weather, and things from the stove.', 'newest', 1774104134, 1774104134);
INSERT INTO "collection" ("id", "title", "description", "sort_order", "created_at", "updated_at") VALUES('col_01km8dhhc8fq895qdnkrjyg77a', 'Reading Notes', 'Lines worth keeping and thoughts after a chapter ends.', 'newest', 1774104135, 1774104135);
INSERT INTO "collection" ("id", "title", "description", "sort_order", "created_at", "updated_at") VALUES('col_01km8dhhwmfqeakqbe8szamzd8', 'Tiny Projects', 'Repairs, setup tweaks, and half-day improvements around the apartment.', 'newest', 1774104135, 1774104135);
INSERT INTO "collection" ("id", "title", "description", "sort_order", "created_at", "updated_at") VALUES('col_01km8dhjd4fq895qedrjbdf8rs', 'Useful Links', 'Articles, tools, recipes, and pages I want to find again.', 'newest', 1774104136, 1774104136);
INSERT INTO "collection" ("id", "title", "description", "sort_order", "created_at", "updated_at") VALUES('col_01km8dhjxbfqeakqc3zd6jvtp6', 'Weekend Notes', 'Small updates from slow Saturdays and Sundays.', 'newest', 1774104136, 1774104136);

-- nav_item
INSERT INTO "nav_item" ("id", "type", "system_key", "label", "url", "position", "created_at", "updated_at") VALUES('nav_01km8dhdypfq895qc46fer989n', 'system', 'collections', 'Collections', '/c', 'a0', 1774104131, 1774104131);
INSERT INTO "nav_item" ("id", "type", "system_key", "label", "url", "position", "created_at", "updated_at") VALUES('nav_01km8dhe6vfqeakqa31jsfey9v', 'system', 'archive', 'Archive', '/archive', 'a1', 1774104131, 1774104131);
INSERT INTO "nav_item" ("id", "type", "system_key", "label", "url", "position", "created_at", "updated_at") VALUES('nav_01km8dhegkfq895qc99xq1nxbj', 'system', 'rss', 'RSS', '/feed', 'a2', 1774104132, 1774104132);
INSERT INTO "nav_item" ("id", "type", "system_key", "label", "url", "position", "created_at", "updated_at") VALUES('nav_01km8dhes0fqeakqabat0p99m8', 'system', 'settings', 'Settings', '/settings', 'a3', 1774104132, 1774104132);

-- collection_directory_item
INSERT INTO "collection_directory_item" ("id", "type", "collection_id", "label", "position", "created_at", "updated_at") VALUES('cdi_01km8dhgfzfq895qdcyccye86j', 'collection', 'col_01km8dhgf6fq895qcxxsd51c5k', NULL, 'a0', 1774104134, 1774104134);
INSERT INTO "collection_directory_item" ("id", "type", "collection_id", "label", "position", "created_at", "updated_at") VALUES('cdi_01km8dhgrmfqeakqb20jyv65ae', 'collection', 'col_01km8dhgrafqeakqanyeweejgq', NULL, 'a1', 1774104134, 1774104134);
INSERT INTO "collection_directory_item" ("id", "type", "collection_id", "label", "position", "created_at", "updated_at") VALUES('cdi_01km8dhhd0fq895qe4xdcnrswe', 'collection', 'col_01km8dhhc8fq895qdnkrjyg77a', NULL, 'a2', 1774104135, 1774104135);
INSERT INTO "collection_directory_item" ("id", "type", "collection_id", "label", "position", "created_at", "updated_at") VALUES('cdi_01km8dhhwxfqeakqbxqwkdsktt', 'collection', 'col_01km8dhhwmfqeakqbe8szamzd8', NULL, 'a3', 1774104135, 1774104135);
INSERT INTO "collection_directory_item" ("id", "type", "collection_id", "label", "position", "created_at", "updated_at") VALUES('cdi_01km8dhjdxfq895qerwgv5n5wq', 'collection', 'col_01km8dhjd4fq895qedrjbdf8rs', NULL, 'a4', 1774104136, 1774104136);
INSERT INTO "collection_directory_item" ("id", "type", "collection_id", "label", "position", "created_at", "updated_at") VALUES('cdi_01km8dhjxrfqeakqckrxnw420h', 'collection', 'col_01km8dhjxbfqeakqc3zd6jvtp6', NULL, 'a5', 1774104136, 1774104136);

-- post
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhmfsfq895qf957g0bwsb', 'note', 'published', 'public', NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Repotted the balcony herbs before breakfast. Basil was dramatic. Mint did not care at all."}]}]}', '<p>Repotted the balcony herbs before breakfast. Basil was dramatic. Mint did not care at all.</p>', 'Repotted the balcony herbs before breakfast. Basil was dramatic. Mint did not care at all.', NULL, NULL, NULL, NULL, 'pst_01km8dhmfsfq895qf957g0bwsb', NULL, 1758960900, 1758991800, 1774104138, 1774104138);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhnprfq895qfzx30zvr1b', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"I keep forgetting that plants mostly want consistency, not inspiration. Fair enough."}]}]}', '<p>I keep forgetting that plants mostly want consistency, not inspiration. Fair enough.</p>', 'I keep forgetting that plants mostly want consistency, not inspiration. Fair enough.', NULL, NULL, NULL, 'pst_01km8dhmfsfq895qf957g0bwsb', 'pst_01km8dhmfsfq895qf957g0bwsb', NULL, 1758963600, 1758963600, 1774104139, 1774104139);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhpb1fq895qgb1d53z76x', 'link', 'published', NULL, NULL, NULL, 'The potting mix guide I keep rereading', 'https://www.rhs.org.uk/plants/types/houseplants/repotting', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Basic, clear, and good for confidence when I start overthinking dirt."}]}]}', '<p>Basic, clear, and good for confidence when I start overthinking dirt.</p>', 'Basic, clear, and good for confidence when I start overthinking dirt.', NULL, NULL, NULL, 'pst_01km8dhmfsfq895qf957g0bwsb', 'pst_01km8dhmfsfq895qf957g0bwsb', NULL, 1758966000, 1758966000, 1774104140, 1774104140);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhqg3fq895qh7syc52a1y', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"By late afternoon the basil was standing up again. I respect a fast recovery."}]}]}', '<p>By late afternoon the basil was standing up again. I respect a fast recovery.</p>', 'By late afternoon the basil was standing up again. I respect a fast recovery.', NULL, NULL, NULL, 'pst_01km8dhmfsfq895qf957g0bwsb', 'pst_01km8dhmfsfq895qf957g0bwsb', NULL, 1758991800, 1758991800, 1774104141, 1774104141);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhr5hfq895qhjtt85sek6', 'link', 'published', 'public', NULL, NULL, 'A night heron field guide for my walk folder', 'https://www.audubon.org/field-guide/bird/black-crowned-night-heron', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Posting this here so I can find it again the next time I see a suspiciously patient bird near the water."}]}]}', '<p>Posting this here so I can find it again the next time I see a suspiciously patient bird near the water.</p>', 'Posting this here so I can find it again the next time I see a suspiciously patient bird near the water.', NULL, NULL, 4, NULL, 'pst_01km8dhr5hfq895qhjtt85sek6', NULL, 1772701800, 1772701800, 1774104142, 1774104142);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhrw1fq895qj1tzpqk70d', 'note', 'published', 'public', NULL, 1774104142, 'A Quiet Saturday After a Busy Week', NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Last week felt like six weeks compressed into five days. I spent most of it answering things, moving things, and promising myself I would slow down later. Today was the later I had in mind."}]},{"type":"paragraph","content":[{"type":"text","text":"Breakfast took an hour. I opened the windows even though it was still cold. I put the phone on the bookshelf and left it there long enough to hear the apartment settle down."}]},{"type":"moreBreak"},{"type":"paragraph","content":[{"type":"text","text":"What helped most was not turning the free day into a project. I made coffee, wiped the kitchen counter, read twenty pages, and sat in the chair by the window without trying to optimize anything."}]},{"type":"paragraph","content":[{"type":"text","text":"A good day does not always need a headline. Sometimes it only needs enough room to happen."}]}]}', '<p>Last week felt like six weeks compressed into five days. I spent most of it answering things, moving things, and promising myself I would slow down later. Today was the later I had in mind.</p><p>Breakfast took an hour. I opened the windows even though it was still cold. I put the phone on the bookshelf and left it there long enough to hear the apartment settle down.</p><!--more--><p>What helped most was not turning the free day into a project. I made coffee, wiped the kitchen counter, read twenty pages, and sat in the chair by the window without trying to optimize anything.</p><p>A good day does not always need a headline. Sometimes it only needs enough room to happen.</p>', 'Last week felt like six weeks compressed into five days. I spent most of it answering things, moving things, and promising myself I would slow down later. Today was the later I had in mind. Breakfast took an hour. I opened the windows even though it was still cold. I put the phone on the bookshelf and left it there long enough to hear the apartment settle down. What helped most was not turning the free day into a project. I made coffee, wiped the kitchen counter, read twenty pages, and sat in the chair by the window without trying to optimize anything. A good day does not always need a headline. Sometimes it only needs enough room to happen.', NULL, 'Last week felt like six weeks compressed into five days. I spent most of it answering things, moving things, and promising myself I would slow down later. Today was the later I had in mind.

Breakfast took an hour. I opened the windows even though it was still cold. I put the phone on the bookshelf and left it there long enough to hear the apartment settle down.', NULL, NULL, 'pst_01km8dhrw1fq895qj1tzpqk70d', NULL, 1754212200, 1754212200, 1774104142, 1774104142);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhswmfq895qjq9mkzbnjt', 'link', 'published', 'public', NULL, NULL, 'Are.na is the only bookmark pile I still revisit', 'https://www.are.na/', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Most saved links disappear into a hole. This one still feels calm enough to browse on purpose."}]}]}', '<p>Most saved links disappear into a hole. This one still feels calm enough to browse on purpose.</p>', 'Most saved links disappear into a hole. This one still feels calm enough to browse on purpose.', NULL, NULL, 4, NULL, 'pst_01km8dhswmfq895qjq9mkzbnjt', NULL, 1760537700, 1760537700, 1774104143, 1774104143);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhv22fq895qkb66pmka1c', 'note', 'published', 'public', NULL, NULL, 'Bought Too Many Lemons Again', NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Came home from the market with a bag of lemons, parsley, eggs, and zero idea what dinner was going to be."}]},{"type":"paragraph","content":[{"type":"text","text":"This keeps happening. I think part of me believes citrus counts as a plan."}]}]}', '<p>Came home from the market with a bag of lemons, parsley, eggs, and zero idea what dinner was going to be.</p><p>This keeps happening. I think part of me believes citrus counts as a plan.</p>', 'Came home from the market with a bag of lemons, parsley, eggs, and zero idea what dinner was going to be. This keeps happening. I think part of me believes citrus counts as a plan.', NULL, 'Came home from the market with a bag of lemons, parsley, eggs, and zero idea what dinner was going to be.

This keeps happening. I think part of me believes citrus counts as a plan.', NULL, NULL, 'pst_01km8dhv22fq895qkb66pmka1c', NULL, 1762680000, 1762680000, 1774104144, 1774104144);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhvnefq895qkxtfxq0az0', 'note', 'published', 'public', NULL, NULL, 'Current Tea Rotation', NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The kitchen shelf is doing a lot of work right now."}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Jasmine for late afternoons"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Black tea when I need to become a person quickly"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Mint tea after dinner when I want the day to stop talking"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"Nothing profound here. I just like having a small system for ordinary comfort."}]}]}', '<p>The kitchen shelf is doing a lot of work right now.</p><ul><li><p>Jasmine for late afternoons</p></li><li><p>Black tea when I need to become a person quickly</p></li><li><p>Mint tea after dinner when I want the day to stop talking</p></li></ul><p>Nothing profound here. I just like having a small system for ordinary comfort.</p>', 'The kitchen shelf is doing a lot of work right now. Jasmine for late afternoons Black tea when I need to become a person quickly Mint tea after dinner when I want the day to stop talking Nothing profound here. I just like having a small system for ordinary comfort.', NULL, 'The kitchen shelf is doing a lot of work right now.

Nothing profound here. I just like having a small system for ordinary comfort.', NULL, NULL, 'pst_01km8dhvnefq895qkxtfxq0az0', NULL, 1757151900, 1757151900, 1774104145, 1774104145);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhw6nfq895qmfc3c70wwv', 'link', 'published', 'public', NULL, NULL, 'Derek Sivers still writes the kind of internet I want more of', 'https://sive.rs/', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Short pages, clear opinions, no inflation. I usually leave with one useful sentence and that is enough."}]}]}', '<p>Short pages, clear opinions, no inflation. I usually leave with one useful sentence and that is enough.</p>', 'Short pages, clear opinions, no inflation. I usually leave with one useful sentence and that is enough.', NULL, NULL, 4, NULL, 'pst_01km8dhw6nfq895qmfc3c70wwv', NULL, 1764060600, 1764060600, 1774104146, 1774104146);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhwrhfq895qmx3hecsf22', 'note', 'published', 'public', 1774104146, NULL, 'Desk, But Better', NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"I finally made the desk simple enough that I want to sit down there again."}]},{"type":"paragraph","content":[{"type":"text","text":"The rule is now: laptop, lamp, notebook, water. If something else lives there, it has to earn the space."}]}]}', '<p>I finally made the desk simple enough that I want to sit down there again.</p><p>The rule is now: laptop, lamp, notebook, water. If something else lives there, it has to earn the space.</p>', 'I finally made the desk simple enough that I want to sit down there again. The rule is now: laptop, lamp, notebook, water. If something else lives there, it has to earn the space.', NULL, 'I finally made the desk simple enough that I want to sit down there again.

The rule is now: laptop, lamp, notebook, water. If something else lives there, it has to earn the space.', NULL, NULL, 'pst_01km8dhwrhfq895qmx3hecsf22', NULL, 1772361900, 1772361900, 1774104146, 1774104146);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhxb5fq895qnekvegjtdb', 'note', 'published', 'public', NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Opened every window this morning and the whole place smelled like rain, old wood, and somebody else''s toast. Good start."}]}]}', '<p>Opened every window this morning and the whole place smelled like rain, old wood, and somebody else&#39;s toast. Good start.</p>', 'Opened every window this morning and the whole place smelled like rain, old wood, and somebody else''s toast. Good start.', NULL, NULL, NULL, NULL, 'pst_01km8dhxb5fq895qnekvegjtdb', NULL, 1754292300, 1754292300, 1774104147, 1774104147);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhxw3fq895qnshd92zqn7', 'quote', 'published', 'public', NULL, NULL, 'From Basho', 'https://en.wikiquote.org/wiki/Matsuo_Basho', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"I like this more the older I get. It makes errands, walks, and ordinary Tuesdays feel less disposable."}]}]}', '<p>I like this more the older I get. It makes errands, walks, and ordinary Tuesdays feel less disposable.</p>', 'I like this more the older I get. It makes errands, walks, and ordinary Tuesdays feel less disposable.', 'Every day is a journey, and the journey itself is home.', NULL, NULL, NULL, 'pst_01km8dhxw3fq895qnshd92zqn7', NULL, 1754987400, 1754987400, 1774104147, 1774104147);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhygdfq895qpb7nt85thm', 'quote', 'published', 'public', NULL, NULL, 'From Epictetus', 'https://en.wikiquote.org/wiki/Epictetus', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"A little stern, maybe. Still useful on the mornings when I drift too long before starting anything."}]}]}', '<p>A little stern, maybe. Still useful on the mornings when I drift too long before starting anything.</p>', 'A little stern, maybe. Still useful on the mornings when I drift too long before starting anything.', 'First say to yourself what you would be; and then do what you have to do.', NULL, NULL, NULL, 'pst_01km8dhygdfq895qpb7nt85thm', NULL, 1770274500, 1770274500, 1774104148, 1774104148);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhz39fq895qpr1f1n8qz3', 'quote', 'published', 'public', NULL, NULL, 'From Marcus Aurelius', 'https://en.wikiquote.org/wiki/Marcus_Aurelius', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Good sentence for the weeks when nothing arrives in the right order and everything needs a little more effort than expected."}]}]}', '<p>Good sentence for the weeks when nothing arrives in the right order and everything needs a little more effort than expected.</p>', 'Good sentence for the weeks when nothing arrives in the right order and everything needs a little more effort than expected.', 'The art of life is more like wrestling than dancing.', NULL, NULL, NULL, 'pst_01km8dhz39fq895qpr1f1n8qz3', NULL, 1756902000, 1756902000, 1774104149, 1774104149);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dhzm0fq895qq8bx65j2ne', 'quote', 'published', 'public', NULL, NULL, 'From Seneca', 'https://en.wikiquote.org/wiki/Seneca_the_Younger', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Copied this onto a sticky note and left it by the monitor for a week. It did its job."}]}]}', '<p>Copied this onto a sticky note and left it by the monitor for a week. It did its job.</p>', 'Copied this onto a sticky note and left it by the monitor for a week. It did its job.', 'While we wait for life, life passes.', NULL, NULL, NULL, 'pst_01km8dhzm0fq895qq8bx65j2ne', NULL, 1765352100, 1765352100, 1774104149, 1774104149);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj04vfq895qqwfzdcspg0', 'quote', 'published', 'public', NULL, NULL, 'From Thoreau', 'https://en.wikiquote.org/wiki/Henry_David_Thoreau', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Useful line before I buy nonsense online because I had a long day and want to feel rewarded."}]}]}', '<p>Useful line before I buy nonsense online because I had a long day and want to feel rewarded.</p>', 'Useful line before I buy nonsense online because I had a long day and want to feel rewarded.', 'The price of anything is the amount of life you exchange for it.', NULL, NULL, NULL, 'pst_01km8dj04vfq895qqwfzdcspg0', NULL, 1761509400, 1761509400, 1774104150, 1774104150);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj1fefq895qrpb55gzyhx', 'note', 'published', 'public', NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Tonight''s tiny project: make the desk usable again without buying a single organizer."}]}]}', '<p>Tonight&#39;s tiny project: make the desk usable again without buying a single organizer.</p>', 'Tonight''s tiny project: make the desk usable again without buying a single organizer.', NULL, NULL, NULL, NULL, 'pst_01km8dj1fefq895qrpb55gzyhx', NULL, 1767811200, 1767816600, 1774104151, 1774104151);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj234fq895qs0gs5vp24f', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The real problem was not cables. It was receipts, pens, and three mugs pretending not to be clutter."}]}]}', '<p>The real problem was not cables. It was receipts, pens, and three mugs pretending not to be clutter.</p>', 'The real problem was not cables. It was receipts, pens, and three mugs pretending not to be clutter.', NULL, NULL, NULL, 'pst_01km8dj1fefq895qrpb55gzyhx', 'pst_01km8dj1fefq895qrpb55gzyhx', NULL, 1767812400, 1767812400, 1774104152, 1774104152);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj3a0fq895qsykz14qxqk', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Thirty minutes later: laptop, lamp, notebook, one glass of water. That is apparently my ideal system."}]}]}', '<p>Thirty minutes later: laptop, lamp, notebook, one glass of water. That is apparently my ideal system.</p>', 'Thirty minutes later: laptop, lamp, notebook, one glass of water. That is apparently my ideal system.', NULL, NULL, NULL, 'pst_01km8dj1fefq895qrpb55gzyhx', 'pst_01km8dj1fefq895qrpb55gzyhx', NULL, 1767813900, 1767813900, 1774104153, 1774104153);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj3yffq895qt9j971rtjv', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"I keep relearning that most home fixes are just decisions I delayed."}]}]}', '<p>I keep relearning that most home fixes are just decisions I delayed.</p>', 'I keep relearning that most home fixes are just decisions I delayed.', NULL, NULL, NULL, 'pst_01km8dj1fefq895qrpb55gzyhx', 'pst_01km8dj1fefq895qrpb55gzyhx', NULL, 1767816600, 1767816600, 1774104154, 1774104154);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj4nefq895qtshe019n8n', 'note', 'published', 'public', NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Went into the bookshop for one notebook and left with a novel, essays, and a coffee I did not need. Classic behavior."}]}]}', '<p>Went into the bookshop for one notebook and left with a novel, essays, and a coffee I did not need. Classic behavior.</p>', 'Went into the bookshop for one notebook and left with a novel, essays, and a coffee I did not need. Classic behavior.', NULL, NULL, NULL, NULL, 'pst_01km8dj4nefq895qtshe019n8n', NULL, 1762083300, 1762092000, 1774104154, 1774104154);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj58xfq895qvcvbsp5jsk', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"I like buying books in person because it slows me down enough to choose one on purpose. Online I become a raccoon with a wallet."}]}]}', '<p>I like buying books in person because it slows me down enough to choose one on purpose. Online I become a raccoon with a wallet.</p>', 'I like buying books in person because it slows me down enough to choose one on purpose. Online I become a raccoon with a wallet.', NULL, NULL, NULL, 'pst_01km8dj4nefq895qtshe019n8n', 'pst_01km8dj4nefq895qtshe019n8n', NULL, 1762088700, 1762088700, 1774104155, 1774104155);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj5z3fq895qvxfr9he4cz', 'quote', 'published', NULL, NULL, NULL, 'From Seneca', 'https://en.wikiquote.org/wiki/Seneca_the_Younger', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Copied this into the back page before I left the cafe."}]}]}', '<p>Copied this into the back page before I left the cafe.</p>', 'Copied this into the back page before I left the cafe.', 'While we wait for life, life passes.', NULL, NULL, 'pst_01km8dj4nefq895qtshe019n8n', 'pst_01km8dj4nefq895qtshe019n8n', NULL, 1762085400, 1762085400, 1774104156, 1774104156);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj6rkfq895qwcqrdp8fdr', 'link', 'published', NULL, NULL, NULL, 'A reading log idea I might steal', 'https://bulletjournal.com/blogs/bulletjournalist/reading-journal', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Not doing all of this, but I like the simple notes-after-finish approach."}]}]}', '<p>Not doing all of this, but I like the simple notes-after-finish approach.</p>', 'Not doing all of this, but I like the simple notes-after-finish approach.', NULL, NULL, NULL, 'pst_01km8dj4nefq895qtshe019n8n', 'pst_01km8dj4nefq895qtshe019n8n', NULL, 1762092000, 1762092000, 1774104156, 1774104156);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj7f8fq895qwzxxc4p9v5', 'link', 'published', 'public', NULL, NULL, 'myNoise for rainy afternoons', 'https://mynoise.net/', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"I open this when the building gets loud and I need a little wall between me and everything else. It is one of the few sites I still bookmark on purpose."}]}]}', '<p>I open this when the building gets loud and I need a little wall between me and everything else. It is one of the few sites I still bookmark on purpose.</p>', 'I open this when the building gets loud and I need a little wall between me and everything else. It is one of the few sites I still bookmark on purpose.', NULL, NULL, 4, NULL, 'pst_01km8dj7f8fq895qwzxxc4p9v5', NULL, 1753105200, 1753105200, 1774104157, 1774104157);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj7zyfq895qxd4f43yt33', 'link', 'published', 'public', NULL, NULL, 'NTS archives are good cleaning music', 'https://www.nts.live/', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"I put this on whenever I need to wash dishes, fold laundry, or stop overthinking a small task. It gives the room a pulse."}]}]}', '<p>I put this on whenever I need to wash dishes, fold laundry, or stop overthinking a small task. It gives the room a pulse.</p>', 'I put this on whenever I need to wash dishes, fold laundry, or stop overthinking a small task. It gives the room a pulse.', NULL, NULL, 4, NULL, 'pst_01km8dj7zyfq895qxd4f43yt33', NULL, 1754733900, 1754733900, 1774104158, 1774104158);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj8hnfq895qxr3vb3hts5', 'note', 'published', 'public', NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Trying a slower Sunday on purpose today. Laundry, soup, no errands, no browser tabs multiplying in the background. Let''s see if that is enough."}]}]}', '<p>Trying a slower Sunday on purpose today. Laundry, soup, no errands, no browser tabs multiplying in the background. Let&#39;s see if that is enough.</p>', 'Trying a slower Sunday on purpose today. Laundry, soup, no errands, no browser tabs multiplying in the background. Let''s see if that is enough.', NULL, NULL, NULL, NULL, 'pst_01km8dj8hnfq895qxr3vb3hts5', NULL, 1756630800, 1756667400, 1774104158, 1774104158);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj91zfq895qyb3rbd604y', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Made a huge pot of lentil soup because future me deserves one easy lunch."}]}]}', '<p>Made a huge pot of lentil soup because future me deserves one easy lunch.</p>', 'Made a huge pot of lentil soup because future me deserves one easy lunch.', NULL, NULL, NULL, 'pst_01km8dj8hnfq895qxr3vb3hts5', 'pst_01km8dj8hnfq895qxr3vb3hts5', NULL, 1756642800, 1756642800, 1774104159, 1774104159);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dj9rgfq895qyvr4t7e83t', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"First win: I put the phone in the bedroom and the apartment immediately got quieter. I should not need this lesson every week, but apparently I do."}]}]}', '<p>First win: I put the phone in the bedroom and the apartment immediately got quieter. I should not need this lesson every week, but apparently I do.</p>', 'First win: I put the phone in the bedroom and the apartment immediately got quieter. I should not need this lesson every week, but apparently I do.', NULL, NULL, NULL, 'pst_01km8dj8hnfq895qxr3vb3hts5', 'pst_01km8dj8hnfq895qxr3vb3hts5', NULL, 1756634700, 1756634700, 1774104160, 1774104160);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djacafq895qz8qmzw85nq', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Ending the day with the floor swept and a book on the table. Very small life. Very good life."}]}]}', '<p>Ending the day with the floor swept and a book on the table. Very small life. Very good life.</p>', 'Ending the day with the floor swept and a book on the table. Very small life. Very good life.', NULL, NULL, NULL, 'pst_01km8dj8hnfq895qxr3vb3hts5', 'pst_01km8dj8hnfq895qxr3vb3hts5', NULL, 1756667400, 1756667400, 1774104160, 1774104160);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djbczfq895r0118372ajb', 'note', 'published', 'public', NULL, 1774104161, 'Rain Makes My Neighborhood Look Better', NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Everything sharpens after a light shower: the crosswalk paint, the leaves stuck to the curb, the bakery sign that usually disappears into the block."}]},{"type":"paragraph","content":[{"type":"text","text":"I took the long way home for no reason other than the street looked newly washed. That was reason enough."}]}]}', '<p>Everything sharpens after a light shower: the crosswalk paint, the leaves stuck to the curb, the bakery sign that usually disappears into the block.</p><p>I took the long way home for no reason other than the street looked newly washed. That was reason enough.</p>', 'Everything sharpens after a light shower: the crosswalk paint, the leaves stuck to the curb, the bakery sign that usually disappears into the block. I took the long way home for no reason other than the street looked newly washed. That was reason enough.', NULL, 'Everything sharpens after a light shower: the crosswalk paint, the leaves stuck to the curb, the bakery sign that usually disappears into the block.

I took the long way home for no reason other than the street looked newly washed. That was reason enough.', NULL, NULL, 'pst_01km8djbczfq895r0118372ajb', NULL, 1771609200, 1771609200, 1774104161, 1774104161);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djc2zfq895r0m9z30cep8', 'link', 'published', 'public', NULL, NULL, 'Serious Eats on tomato and egg soup', 'https://www.seriouseats.com/tomato-egg-drop-soup-recipe-8705599', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"This is the kind of recipe I trust on a tired weeknight. Short ingredient list, no drama, and it tastes like you tried harder than you did."}]}]}', '<p>This is the kind of recipe I trust on a tired weeknight. Short ingredient list, no drama, and it tastes like you tried harder than you did.</p>', 'This is the kind of recipe I trust on a tired weeknight. Short ingredient list, no drama, and it tastes like you tried harder than you did.', NULL, NULL, 5, NULL, 'pst_01km8djc2zfq895r0m9z30cep8', NULL, 1758130200, 1758130200, 1774104162, 1774104162);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djd28fq895r1awr8rm5v4', 'note', 'published', 'public', NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Made tomato soup because the weather could not decide what month it wanted to be."}]}]}', '<p>Made tomato soup because the weather could not decide what month it wanted to be.</p>', 'Made tomato soup because the weather could not decide what month it wanted to be.', NULL, NULL, NULL, NULL, 'pst_01km8djd28fq895r1awr8rm5v4', NULL, 1769946900, 1769969100, 1774104163, 1774104163);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djdnxfq895r1vx7zgjbz7', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Added a grilled cheese with too much mustard and it turned out to be exactly the right amount of mustard."}]}]}', '<p>Added a grilled cheese with too much mustard and it turned out to be exactly the right amount of mustard.</p>', 'Added a grilled cheese with too much mustard and it turned out to be exactly the right amount of mustard.', NULL, NULL, NULL, 'pst_01km8djd28fq895r1awr8rm5v4', 'pst_01km8djd28fq895r1awr8rm5v4', NULL, 1769950200, 1769950200, 1774104164, 1774104164);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8dje8zfq895r2e37zf1s4a', 'link', 'published', NULL, NULL, NULL, 'The soup trick I always forget', 'https://www.seriouseats.com/15-minute-creamy-tomato-soup-vegan-recipe', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Butter first, then onions. It changes the whole pot."}]}]}', '<p>Butter first, then onions. It changes the whole pot.</p>', 'Butter first, then onions. It changes the whole pot.', NULL, NULL, NULL, 'pst_01km8djd28fq895r1awr8rm5v4', 'pst_01km8djd28fq895r1awr8rm5v4', NULL, 1769948400, 1769948400, 1774104164, 1774104164);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djf85fq895r2x7tk71rbt', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Leftovers tomorrow, which means future me already won."}]}]}', '<p>Leftovers tomorrow, which means future me already won.</p>', 'Leftovers tomorrow, which means future me already won.', NULL, NULL, NULL, 'pst_01km8djd28fq895r1awr8rm5v4', 'pst_01km8djd28fq895r1awr8rm5v4', NULL, 1769969100, 1769969100, 1774104165, 1774104165);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djfx6fq895r3927kmxq0p', 'note', 'published', 'public', NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Took the long way home because the light was good and the air finally felt like spring."}]}]}', '<p>Took the long way home because the light was good and the air finally felt like spring.</p>', 'Took the long way home because the light was good and the air finally felt like spring.', NULL, NULL, NULL, NULL, 'pst_01km8djfx6fq895r3927kmxq0p', NULL, 1773076500, 1773081000, 1774104166, 1774104166);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djgevfq895r3w98sdbtv0', 'link', 'published', NULL, NULL, NULL, 'OpenStreetMap for route wandering', 'https://www.openstreetmap.org/', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Still the best place to find side streets I would otherwise miss."}]}]}', '<p>Still the best place to find side streets I would otherwise miss.</p>', 'Still the best place to find side streets I would otherwise miss.', NULL, NULL, NULL, 'pst_01km8djfx6fq895r3927kmxq0p', 'pst_01km8djfx6fq895r3927kmxq0p', NULL, 1773081000, 1773081000, 1774104166, 1774104166);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djh82fq895r4dn62d8vcr', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Passed the flower stall, the old bakery, and the repair shop with the radio on. Same route, different mood every time."}]}]}', '<p>Passed the flower stall, the old bakery, and the repair shop with the radio on. Same route, different mood every time.</p>', 'Passed the flower stall, the old bakery, and the repair shop with the radio on. Same route, different mood every time.', NULL, NULL, NULL, 'pst_01km8djfx6fq895r3927kmxq0p', 'pst_01km8djfx6fq895r3927kmxq0p', NULL, 1773078000, 1773078000, 1774104167, 1774104167);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djhvhfq895r4xmfyqcp4s', 'quote', 'published', NULL, NULL, NULL, 'From Thoreau', 'https://en.wikiquote.org/wiki/Henry_David_Thoreau', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Thought about this while deciding not to call a car for the last mile."}]}]}', '<p>Thought about this while deciding not to call a car for the last mile.</p>', 'Thought about this while deciding not to call a car for the last mile.', 'The price of anything is the amount of life you exchange for it.', NULL, NULL, 'pst_01km8djfx6fq895r3927kmxq0p', 'pst_01km8djfx6fq895r3927kmxq0p', NULL, 1773079500, 1773079500, 1774104168, 1774104168);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djjf7fq895r5bwm4hgh44', 'note', 'published', 'public', NULL, NULL, 'The Five-Minute Reset Is Still the Best Habit I Have', NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"When the apartment starts feeling loud, I set a five-minute timer and do the same small loop:"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"dishes into the sink"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"clothes off the chair"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"papers into one stack"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"window cracked open"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"It does not fix everything, but it changes the room enough that I stop feeling stuck in it."}]}]}', '<p>When the apartment starts feeling loud, I set a five-minute timer and do the same small loop:</p><ul><li><p>dishes into the sink</p></li><li><p>clothes off the chair</p></li><li><p>papers into one stack</p></li><li><p>window cracked open</p></li></ul><p>It does not fix everything, but it changes the room enough that I stop feeling stuck in it.</p>', 'When the apartment starts feeling loud, I set a five-minute timer and do the same small loop: dishes into the sink clothes off the chair papers into one stack window cracked open It does not fix everything, but it changes the room enough that I stop feeling stuck in it.', NULL, 'When the apartment starts feeling loud, I set a five-minute timer and do the same small loop:

It does not fix everything, but it changes the room enough that I stop feeling stuck in it.', NULL, NULL, 'pst_01km8djjf7fq895r5bwm4hgh44', NULL, 1768244400, 1768244400, 1774104168, 1774104168);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djjzxfq895r5weprd9sjt', 'note', 'published', 'public', NULL, NULL, 'The Hallway Light Took 12 Minutes and 3 Months', NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"The bulb burned out in June. I meant to replace it the same day. Instead I spent three months walking through the hallway like somebody in a low-budget mystery movie."}]},{"type":"paragraph","content":[{"type":"text","text":"Today I bought the new bulb, climbed the stool, changed it, and laughed at how small the actual job was."}]},{"type":"paragraph","content":[{"type":"text","text":"This is the kind of tiny project I avoid for no good reason. The dread is usually larger than the task."}]}]}', '<p>The bulb burned out in June. I meant to replace it the same day. Instead I spent three months walking through the hallway like somebody in a low-budget mystery movie.</p><p>Today I bought the new bulb, climbed the stool, changed it, and laughed at how small the actual job was.</p><p>This is the kind of tiny project I avoid for no good reason. The dread is usually larger than the task.</p>', 'The bulb burned out in June. I meant to replace it the same day. Instead I spent three months walking through the hallway like somebody in a low-budget mystery movie. Today I bought the new bulb, climbed the stool, changed it, and laughed at how small the actual job was. This is the kind of tiny project I avoid for no good reason. The dread is usually larger than the task.', NULL, 'The bulb burned out in June. I meant to replace it the same day. Instead I spent three months walking through the hallway like somebody in a low-budget mystery movie.

Today I bought the new bulb, climbed the stool, changed it, and laughed at how small the actual job was.

This is the kind of tiny project I avoid for no good reason. The dread is usually larger than the task.', NULL, NULL, 'pst_01km8djjzxfq895r5weprd9sjt', NULL, 1755540600, 1755540600, 1774104169, 1774104169);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djkjefq895r68vvhgm8bn', 'link', 'published', 'public', NULL, NULL, 'The Recurse Center manual is weirdly calming', 'https://www.recurse.com/manual', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"I like reading pages where people have thought hard about how they want to work together. This one always makes me want to clean up my own habits."}]}]}', '<p>I like reading pages where people have thought hard about how they want to work together. This one always makes me want to clean up my own habits.</p>', 'I like reading pages where people have thought hard about how they want to work together. This one always makes me want to clean up my own habits.', NULL, NULL, 5, NULL, 'pst_01km8djkjefq895r68vvhgm8bn', NULL, 1769700000, 1769700000, 1774104170, 1774104170);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djm37fq895r6rcxjbzjj1', 'note', 'published', 'public', NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Took the long way home because the light was good and the air finally felt like spring."}]}]}', '<p>Took the long way home because the light was good and the air finally felt like spring.</p>', 'Took the long way home because the light was good and the air finally felt like spring.', NULL, NULL, NULL, NULL, 'pst_01km8djm37fq895r6rcxjbzjj1', NULL, 1773076500, 1773081000, 1774104170, 1774104170);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djmktfq895r78r340gsdv', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Passed the flower stall, the old bakery, and the repair shop with the radio on. Same route, different mood every time."}]}]}', '<p>Passed the flower stall, the old bakery, and the repair shop with the radio on. Same route, different mood every time.</p>', 'Passed the flower stall, the old bakery, and the repair shop with the radio on. Same route, different mood every time.', NULL, NULL, NULL, 'pst_01km8djm37fq895r6rcxjbzjj1', 'pst_01km8djm37fq895r6rcxjbzjj1', NULL, 1773078000, 1773078000, 1774104171, 1774104171);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djn80fq895r7w4hjxef5w', 'link', 'published', NULL, NULL, NULL, 'A bird guide for slow walks', 'https://www.audubon.org/field-guide/bird/black-crowned-night-heron', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Mostly posting this here so I can find it again next weekend."}]}]}', '<p>Mostly posting this here so I can find it again next weekend.</p>', 'Mostly posting this here so I can find it again next weekend.', NULL, NULL, NULL, 'pst_01km8djm37fq895r6rcxjbzjj1', 'pst_01km8djm37fq895r6rcxjbzjj1', NULL, 1773081000, 1773081000, 1774104171, 1774104171);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djnv3fq895r8fspxqp28y', 'quote', 'published', NULL, NULL, NULL, 'From Thoreau', 'https://en.wikiquote.org/wiki/Henry_David_Thoreau', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Thought about this while deciding not to call a car for the last mile."}]}]}', '<p>Thought about this while deciding not to call a car for the last mile.</p>', 'Thought about this while deciding not to call a car for the last mile.', 'The price of anything is the amount of life you exchange for it.', NULL, NULL, 'pst_01km8djm37fq895r6rcxjbzjj1', 'pst_01km8djm37fq895r6rcxjbzjj1', NULL, 1773079500, 1773079500, 1774104172, 1774104172);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djpvcfq895r93m6feb6dt', 'note', 'published', 'public', NULL, 1774104173, 'What I Actually Use My Notebook For', NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"I always imagine I will use a fresh notebook for my best thoughts. In reality, it becomes useful much sooner and in messier ways."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Mostly three things"}]},{"type":"orderedList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Shopping lists"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Fragments I do not trust my phone with"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"The first ugly version of an idea"}]}]}]},{"type":"paragraph","content":[{"type":"text","text":"That turns out to be enough. A notebook does not need to become an archive. It only needs to catch the thought before it slips away."}]}]}', '<p>I always imagine I will use a fresh notebook for my best thoughts. In reality, it becomes useful much sooner and in messier ways.</p><h2>Mostly three things</h2><ol><li><p>Shopping lists</p></li><li><p>Fragments I do not trust my phone with</p></li><li><p>The first ugly version of an idea</p></li></ol><p>That turns out to be enough. A notebook does not need to become an archive. It only needs to catch the thought before it slips away.</p>', 'I always imagine I will use a fresh notebook for my best thoughts. In reality, it becomes useful much sooner and in messier ways. Mostly three things Shopping lists Fragments I do not trust my phone with The first ugly version of an idea That turns out to be enough. A notebook does not need to become an archive. It only needs to catch the thought before it slips away.', NULL, 'I always imagine I will use a fresh notebook for my best thoughts. In reality, it becomes useful much sooner and in messier ways.

That turns out to be enough. A notebook does not need to become an archive. It only needs to catch the thought before it slips away.', NULL, NULL, 'pst_01km8djpvcfq895r93m6feb6dt', NULL, 1759402800, 1759402800, 1774104173, 1774104173);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djqd9fq895r9pbyf0eb0h', 'note', 'published', 'public', NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Made tomato soup because the weather could not decide what month it wanted to be."}]}]}', '<p>Made tomato soup because the weather could not decide what month it wanted to be.</p>', 'Made tomato soup because the weather could not decide what month it wanted to be.', NULL, NULL, NULL, NULL, 'pst_01km8djqd9fq895r9pbyf0eb0h', NULL, 1769946900, 1769969100, 1774104173, 1774104173);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djqxvfq895ra79pp3yr93', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Leftovers tomorrow, which means future me already won."}]}]}', '<p>Leftovers tomorrow, which means future me already won.</p>', 'Leftovers tomorrow, which means future me already won.', NULL, NULL, NULL, 'pst_01km8djqd9fq895r9pbyf0eb0h', 'pst_01km8djqd9fq895r9pbyf0eb0h', NULL, 1769969100, 1769969100, 1774104174, 1774104174);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djrgjfq895ranrwa723d7', 'link', 'published', NULL, NULL, NULL, 'The soup trick I always forget', 'https://www.seriouseats.com/15-minute-creamy-tomato-soup-vegan-recipe', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Butter first, then onions. It changes the whole pot."}]}]}', '<p>Butter first, then onions. It changes the whole pot.</p>', 'Butter first, then onions. It changes the whole pot.', NULL, NULL, NULL, 'pst_01km8djqd9fq895r9pbyf0eb0h', 'pst_01km8djqd9fq895r9pbyf0eb0h', NULL, 1769948400, 1769948400, 1774104175, 1774104175);
INSERT INTO "post" ("id", "format", "status", "visibility", "pinned_at", "featured_at", "title", "url", "body", "body_html", "body_text", "quote_text", "summary", "rating", "reply_to_id", "thread_id", "deleted_at", "published_at", "last_activity_at", "created_at", "updated_at") VALUES('pst_01km8djs68fq895rb0ayd5zskk', 'note', 'published', NULL, NULL, NULL, NULL, NULL, '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Added a grilled cheese with too much mustard and it turned out to be exactly the right amount of mustard."}]}]}', '<p>Added a grilled cheese with too much mustard and it turned out to be exactly the right amount of mustard.</p>', 'Added a grilled cheese with too much mustard and it turned out to be exactly the right amount of mustard.', NULL, NULL, NULL, 'pst_01km8djqd9fq895r9pbyf0eb0h', 'pst_01km8djqd9fq895r9pbyf0eb0h', NULL, 1769950200, 1769950200, 1774104175, 1774104175);

-- post_collection
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhmfsfq895qf957g0bwsb', 'col_01km8dhhwmfqeakqbe8szamzd8', 1774104138);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhmfsfq895qf957g0bwsb', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104138);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhr5hfq895qhjtt85sek6', 'col_01km8dhgf6fq895qcxxsd51c5k', 1774104142);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhr5hfq895qhjtt85sek6', 'col_01km8dhjd4fq895qedrjbdf8rs', 1774104142);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhrw1fq895qj1tzpqk70d', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104142);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhswmfq895qjq9mkzbnjt', 'col_01km8dhhwmfqeakqbe8szamzd8', 1774104143);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhswmfq895qjq9mkzbnjt', 'col_01km8dhjd4fq895qedrjbdf8rs', 1774104143);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhv22fq895qkb66pmka1c', 'col_01km8dhgrafqeakqanyeweejgq', 1774104144);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhvnefq895qkxtfxq0az0', 'col_01km8dhgrafqeakqanyeweejgq', 1774104145);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhvnefq895qkxtfxq0az0', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104145);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhw6nfq895qmfc3c70wwv', 'col_01km8dhhc8fq895qdnkrjyg77a', 1774104146);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhw6nfq895qmfc3c70wwv', 'col_01km8dhjd4fq895qedrjbdf8rs', 1774104146);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhwrhfq895qmx3hecsf22', 'col_01km8dhhwmfqeakqbe8szamzd8', 1774104146);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhxb5fq895qnekvegjtdb', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104147);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhxw3fq895qnshd92zqn7', 'col_01km8dhhc8fq895qdnkrjyg77a', 1774104147);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhygdfq895qpb7nt85thm', 'col_01km8dhhc8fq895qdnkrjyg77a', 1774104148);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhz39fq895qpr1f1n8qz3', 'col_01km8dhhc8fq895qdnkrjyg77a', 1774104149);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dhzm0fq895qq8bx65j2ne', 'col_01km8dhhc8fq895qdnkrjyg77a', 1774104149);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj04vfq895qqwfzdcspg0', 'col_01km8dhhc8fq895qdnkrjyg77a', 1774104150);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj1fefq895qrpb55gzyhx', 'col_01km8dhhwmfqeakqbe8szamzd8', 1774104151);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj4nefq895qtshe019n8n', 'col_01km8dhhc8fq895qdnkrjyg77a', 1774104154);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj4nefq895qtshe019n8n', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104154);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj7f8fq895qwzxxc4p9v5', 'col_01km8dhjd4fq895qedrjbdf8rs', 1774104157);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj7f8fq895qwzxxc4p9v5', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104157);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj7zyfq895qxd4f43yt33', 'col_01km8dhjd4fq895qedrjbdf8rs', 1774104158);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj7zyfq895qxd4f43yt33', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104158);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj8hnfq895qxr3vb3hts5', 'col_01km8dhgrafqeakqanyeweejgq', 1774104158);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8dj8hnfq895qxr3vb3hts5', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104158);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djbczfq895r0118372ajb', 'col_01km8dhgf6fq895qcxxsd51c5k', 1774104161);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djbczfq895r0118372ajb', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104161);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djc2zfq895r0m9z30cep8', 'col_01km8dhgrafqeakqanyeweejgq', 1774104162);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djc2zfq895r0m9z30cep8', 'col_01km8dhjd4fq895qedrjbdf8rs', 1774104162);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djd28fq895r1awr8rm5v4', 'col_01km8dhgrafqeakqanyeweejgq', 1774104163);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djd28fq895r1awr8rm5v4', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104163);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djfx6fq895r3927kmxq0p', 'col_01km8dhgf6fq895qcxxsd51c5k', 1774104166);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djfx6fq895r3927kmxq0p', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104166);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djjf7fq895r5bwm4hgh44', 'col_01km8dhhwmfqeakqbe8szamzd8', 1774104168);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djjf7fq895r5bwm4hgh44', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104168);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djjzxfq895r5weprd9sjt', 'col_01km8dhhwmfqeakqbe8szamzd8', 1774104169);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djjzxfq895r5weprd9sjt', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104169);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djkjefq895r68vvhgm8bn', 'col_01km8dhhwmfqeakqbe8szamzd8', 1774104170);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djkjefq895r68vvhgm8bn', 'col_01km8dhjd4fq895qedrjbdf8rs', 1774104170);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djm37fq895r6rcxjbzjj1', 'col_01km8dhgf6fq895qcxxsd51c5k', 1774104170);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djm37fq895r6rcxjbzjj1', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104170);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djpvcfq895r93m6feb6dt', 'col_01km8dhhwmfqeakqbe8szamzd8', 1774104173);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djpvcfq895r93m6feb6dt', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104173);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djqd9fq895r9pbyf0eb0h', 'col_01km8dhgrafqeakqanyeweejgq', 1774104173);
INSERT INTO "post_collection" ("post_id", "collection_id", "created_at") VALUES('pst_01km8djqd9fq895r9pbyf0eb0h', 'col_01km8dhjxbfqeakqc3zd6jvtp6', 1774104173);

-- path_registry
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhnrhfq895qg27rnxj20t', '0x4nv', 'slug', 'pst_01km8dhnprfq895qfzx30zvr1b', NULL, NULL, NULL, 1774104139, 1774104139);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj405fq895qtj5a4rxkw8', '2cl6d', 'slug', 'pst_01km8dj3yffq895qt9j971rtjv', NULL, NULL, NULL, 1774104154, 1774104154);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djs7gfq895rbekq4f6rht', '3gu1a', 'slug', 'pst_01km8djs68fq895rb0ayd5zskk', NULL, NULL, NULL, 1774104175, 1774104175);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj3b6fq895qt3e50gnpjr', '3zqv7', 'slug', 'pst_01km8dj3a0fq895qsykz14qxqk', NULL, NULL, NULL, 1774104153, 1774104153);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhmg7fq895qfjx96vrzmr', '41q27', 'slug', 'pst_01km8dhmfsfq895qf957g0bwsb', NULL, NULL, NULL, 1774104138, 1774104138);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj24tfq895qs82fk3zef5', '5oxsv', 'slug', 'pst_01km8dj234fq895qs0gs5vp24f', NULL, NULL, NULL, 1774104152, 1774104152);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djqz7fq895raa502knxr4', '92nih', 'slug', 'pst_01km8djqxvfq895ra79pp3yr93', NULL, NULL, NULL, 1774104174, 1774104174);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djh9afq895r4nqfjhcxn8', '9gqsf', 'slug', 'pst_01km8djh82fq895r4dn62d8vcr', NULL, NULL, NULL, 1774104167, 1774104167);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djn98fq895r860p5fnwzb', 'a-bird-guide-for-slow-walks', 'slug', 'pst_01km8djn80fq895r7w4hjxef5w', NULL, NULL, NULL, 1774104171, 1774104171);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhr67fq895qhra2hbcsg3', 'a-night-heron-field-guide-for-my-walk-folder', 'slug', 'pst_01km8dhr5hfq895qhjtt85sek6', NULL, NULL, NULL, 1774104142, 1774104142);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhrwefq895qj99qaesd28', 'a-quiet-saturday-after-a-busy-week', 'slug', 'pst_01km8dhrw1fq895qj1tzpqk70d', NULL, NULL, NULL, 1774104142, 1774104142);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj6sxfq895qwgzcn0z6v7', 'a-reading-log-idea-i-might-steal', 'slug', 'pst_01km8dj6rkfq895qwcqrdp8fdr', NULL, NULL, NULL, 1774104156, 1774104156);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj5a6fq895qvqsdx4y9cp', 'a83qu', 'slug', 'pst_01km8dj58xfq895qvcvbsp5jsk', NULL, NULL, NULL, 1774104155, 1774104155);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhsx6fq895qjszzv4nn4q', 'are-na-is-the-only-bookmark-pile-i-still-revisit', 'slug', 'pst_01km8dhswmfq895qjq9mkzbnjt', NULL, NULL, NULL, 1774104143, 1774104143);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhv2afq895qkmrs5wfr8g', 'bought-too-many-lemons-again', 'slug', 'pst_01km8dhv22fq895qkb66pmka1c', NULL, NULL, NULL, 1774104144, 1774104144);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhgfzfq895qd4reftbasm', 'c/city-walks', 'slug', NULL, 'col_01km8dhgf6fq895qcxxsd51c5k', NULL, NULL, 1774104134, 1774104134);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhgrmfqeakqavss4rdemz', 'c/home-cooking', 'slug', NULL, 'col_01km8dhgrafqeakqanyeweejgq', NULL, NULL, 1774104134, 1774104134);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhhd0fq895qdsdcapt0k5', 'c/reading-notes', 'slug', NULL, 'col_01km8dhhc8fq895qdnkrjyg77a', NULL, NULL, 1774104135, 1774104135);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhhwxfqeakqbnx7v2nt0s', 'c/tiny-projects', 'slug', NULL, 'col_01km8dhhwmfqeakqbe8szamzd8', NULL, NULL, 1774104135, 1774104135);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhjdxfq895qehnsf88hqr', 'c/useful-links', 'slug', NULL, 'col_01km8dhjd4fq895qedrjbdf8rs', NULL, NULL, 1774104136, 1774104136);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhjxrfqeakqcbp2gk1a5x', 'c/weekend-notes', 'slug', NULL, 'col_01km8dhjxbfqeakqc3zd6jvtp6', NULL, NULL, 1774104136, 1774104136);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj9t2fq895qz4j302kjbg', 'c91j0', 'slug', 'pst_01km8dj9rgfq895qyvr4t7e83t', NULL, NULL, NULL, 1774104160, 1774104160);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhvntfq895qm37j7braa4', 'current-tea-rotation', 'slug', 'pst_01km8dhvnefq895qkxtfxq0az0', NULL, NULL, NULL, 1774104145, 1774104145);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djf9dfq895r37gy2msg6g', 'cxiu6', 'slug', 'pst_01km8djf85fq895r2x7tk71rbt', NULL, NULL, NULL, 1774104165, 1774104165);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhw7efq895qmghkjxc1vq', 'derek-sivers-still-writes-the-kind-of-internet-i-want-more-of', 'slug', 'pst_01km8dhw6nfq895qmfc3c70wwv', NULL, NULL, NULL, 1774104146, 1774104146);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhwrxfq895qn0s6xf5232', 'desk-but-better', 'slug', 'pst_01km8dhwrhfq895qmx3hecsf22', NULL, NULL, NULL, 1774104146, 1774104146);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhxbvfq895qnm7m7k14wr', 'e0kcg', 'slug', 'pst_01km8dhxb5fq895qnekvegjtdb', NULL, NULL, NULL, 1774104147, 1774104147);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djmncfq895r7p78hkvrmr', 'eiwp8', 'slug', 'pst_01km8djmktfq895r78r340gsdv', NULL, NULL, NULL, 1774104171, 1774104171);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhqh7fq895qh9kj2hpvjs', 'faqyt', 'slug', 'pst_01km8dhqg3fq895qh7syc52a1y', NULL, NULL, NULL, 1774104141, 1774104141);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhxwgfq895qp0j2frw3y6', 'from-basho', 'slug', 'pst_01km8dhxw3fq895qnshd92zqn7', NULL, NULL, NULL, 1774104147, 1774104147);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhygvfq895qph2x1t2tts', 'from-epictetus', 'slug', 'pst_01km8dhygdfq895qpb7nt85thm', NULL, NULL, NULL, 1774104148, 1774104148);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhz3zfq895qq4302m5tya', 'from-marcus-aurelius', 'slug', 'pst_01km8dhz39fq895qpr1f1n8qz3', NULL, NULL, NULL, 1774104149, 1774104149);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhzmefq895qqqpcdmw7wf', 'from-seneca', 'slug', 'pst_01km8dhzm0fq895qq8bx65j2ne', NULL, NULL, NULL, 1774104149, 1774104149);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj60mfq895qw5a7x9dpay', 'from-seneca-5hibo', 'slug', 'pst_01km8dj5z3fq895qvxfr9he4cz', NULL, NULL, NULL, 1774104156, 1774104156);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj05gfq895qr75n1hbg7y', 'from-thoreau', 'slug', 'pst_01km8dj04vfq895qqwfzdcspg0', NULL, NULL, NULL, 1774104150, 1774104150);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djhx2fq895r53q76860wv', 'from-thoreau-pawt2', 'slug', 'pst_01km8djhvhfq895r4xmfyqcp4s', NULL, NULL, NULL, 1774104168, 1774104168);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djnwtfq895r8n5f1bxmtt', 'from-thoreau-ubv9l', 'slug', 'pst_01km8djnv3fq895r8fspxqp28y', NULL, NULL, NULL, 1774104172, 1774104172);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj1frfq895qrsjdjzmzr3', 'gkbvv', 'slug', 'pst_01km8dj1fefq895qrpb55gzyhx', NULL, NULL, NULL, 1774104151, 1774104151);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj4nxfq895qv33tfjsc5e', 'k5vh8', 'slug', 'pst_01km8dj4nefq895qtshe019n8n', NULL, NULL, NULL, 1774104154, 1774104154);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj7fpfq895qx3jp1e5etx', 'mynoise-for-rainy-afternoons', 'slug', 'pst_01km8dj7f8fq895qwzxxc4p9v5', NULL, NULL, NULL, 1774104157, 1774104157);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj80kfq895qxn80h8zkz9', 'nts-archives-are-good-cleaning-music', 'slug', 'pst_01km8dj7zyfq895qxd4f43yt33', NULL, NULL, NULL, 1774104158, 1774104158);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djgg6fq895r42ryeydvps', 'openstreetmap-for-route-wandering', 'slug', 'pst_01km8djgevfq895r3w98sdbtv0', NULL, NULL, NULL, 1774104166, 1774104166);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj8j3fq895qy4gbfpeaaj', 'qgfcu', 'slug', 'pst_01km8dj8hnfq895qxr3vb3hts5', NULL, NULL, NULL, 1774104158, 1774104158);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djadffq895qzh3rpjfy97', 'qyucy', 'slug', 'pst_01km8djacafq895qz8qmzw85nq', NULL, NULL, NULL, 1774104160, 1774104160);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djbd7fq895r08d37de25j', 'rain-makes-my-neighborhood-look-better', 'slug', 'pst_01km8djbczfq895r0118372ajb', NULL, NULL, NULL, 1774104161, 1774104161);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djc3bfq895r0z3jftgden', 'serious-eats-on-tomato-and-egg-soup', 'slug', 'pst_01km8djc2zfq895r0m9z30cep8', NULL, NULL, NULL, 1774104162, 1774104162);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djdqgfq895r25m42690ns', 't77ms', 'slug', 'pst_01km8djdnxfq895r1vx7zgjbz7', NULL, NULL, NULL, 1774104164, 1774104164);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djd2hfq895r1nb80033kn', 'te812', 'slug', 'pst_01km8djd28fq895r1awr8rm5v4', NULL, NULL, NULL, 1774104163, 1774104163);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djfxgfq895r3hxk81djrh', 'telk3', 'slug', 'pst_01km8djfx6fq895r3927kmxq0p', NULL, NULL, NULL, 1774104166, 1774104166);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djjfjfq895r5jg7mqq3vm', 'the-five-minute-reset-is-still-the-best-habit-i-have', 'slug', 'pst_01km8djjf7fq895r5bwm4hgh44', NULL, NULL, NULL, 1774104168, 1774104168);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djk09fq895r64tap1xqj9', 'the-hallway-light-took-12-minutes-and-3-months', 'slug', 'pst_01km8djjzxfq895r5weprd9sjt', NULL, NULL, NULL, 1774104169, 1774104169);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dhpd1fq895qgptdk5gykh', 'the-potting-mix-guide-i-keep-rereading', 'slug', 'pst_01km8dhpb1fq895qgb1d53z76x', NULL, NULL, NULL, 1774104140, 1774104140);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djkk5fq895r6m7q66dj75', 'the-recurse-center-manual-is-weirdly-calming', 'slug', 'pst_01km8djkjefq895r68vvhgm8bn', NULL, NULL, NULL, 1774104170, 1774104170);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djea5fq895r2k61xceyk0', 'the-soup-trick-i-always-forget', 'slug', 'pst_01km8dje8zfq895r2e37zf1s4a', NULL, NULL, NULL, 1774104164, 1774104164);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djrmffq895rarkgmw550s', 'the-soup-trick-i-always-forget-25e01', 'slug', 'pst_01km8djrgjfq895ranrwa723d7', NULL, NULL, NULL, 1774104175, 1774104175);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djm3jfq895r71hywaqb1d', 'u08bn', 'slug', 'pst_01km8djm37fq895r6rcxjbzjj1', NULL, NULL, NULL, 1774104170, 1774104170);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djpvrfq895r9ervpvjkyj', 'what-i-actually-use-my-notebook-for', 'slug', 'pst_01km8djpvcfq895r93m6feb6dt', NULL, NULL, NULL, 1774104173, 1774104173);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8dj93hfq895qym2p143c7q', 'wsgck', 'slug', 'pst_01km8dj91zfq895qyb3rbd604y', NULL, NULL, NULL, 1774104159, 1774104159);
INSERT INTO "path_registry" ("id", "path", "kind", "post_id", "collection_id", "redirect_to_path", "redirect_type", "created_at", "updated_at") VALUES('pth_01km8djqdqfq895r9vwegvpynh', 'z4s9v', 'slug', 'pst_01km8djqd9fq895r9pbyf0eb0h', NULL, NULL, NULL, 1774104173, 1774104173);

-- media
INSERT INTO "media" ("id", "post_id", "filename", "original_name", "mime_type", "size", "storage_key", "provider", "width", "height", "alt", "position", "blurhash", "waveform", "poster_key", "summary", "chars", "media_kind", "created_at", "updated_at") VALUES('med_01km8dhfjafq895qcp3myds3fr', NULL, 'med_01km8dhfjafq895qcp3myds3fr.png', 'f7a9dfac6406-019d0d20-ee44-77c1-8400-5ff85eb2fb5d.png', 'image/png', 19874, 'media/med_01km8dhfjafq895qcp3myds3fr.png', 'r2', NULL, NULL, NULL, 'a0', NULL, NULL, NULL, NULL, NULL, 'image', 1774104133, 1774104133);
INSERT INTO "media" ("id", "post_id", "filename", "original_name", "mime_type", "size", "storage_key", "provider", "width", "height", "alt", "position", "blurhash", "waveform", "poster_key", "summary", "chars", "media_kind", "created_at", "updated_at") VALUES('med_01km8dhkykfq895qf2exh2jne8', 'pst_01km8dhmfsfq895qf957g0bwsb', 'med_01km8dhkykfq895qf2exh2jne8.svg', 'herbs-window.svg', 'image/svg+xml', 892, 'media/med_01km8dhkykfq895qf2exh2jne8.svg', 'r2', 1200, 900, NULL, 'a0', NULL, NULL, NULL, NULL, NULL, 'image', 1774104137, 1774104138);
INSERT INTO "media" ("id", "post_id", "filename", "original_name", "mime_type", "size", "storage_key", "provider", "width", "height", "alt", "position", "blurhash", "waveform", "poster_key", "summary", "chars", "media_kind", "created_at", "updated_at") VALUES('med_01km8dhq2afq895qgy4meqm4r4', 'pst_01km8dhqg3fq895qh7syc52a1y', 'med_01km8dhq2afq895qgy4meqm4r4.svg', 'balcony-light.svg', 'image/svg+xml', 901, 'media/med_01km8dhq2afq895qgy4meqm4r4.svg', 'r2', 1200, 900, NULL, 'a0', NULL, NULL, NULL, NULL, NULL, 'image', 1774104141, 1774104141);
INSERT INTO "media" ("id", "post_id", "filename", "original_name", "mime_type", "size", "storage_key", "provider", "width", "height", "alt", "position", "blurhash", "waveform", "poster_key", "summary", "chars", "media_kind", "created_at", "updated_at") VALUES('med_01km8dhtp0fq895qk2xe66dd08', 'pst_01km8dhv22fq895qkb66pmka1c', 'med_01km8dhtp0fq895qk2xe66dd08.svg', 'market-lemons.svg', 'image/svg+xml', 890, 'media/med_01km8dhtp0fq895qk2xe66dd08.svg', 'r2', 1200, 900, NULL, 'a0', NULL, NULL, NULL, NULL, NULL, 'image', 1774104144, 1774104145);
INSERT INTO "media" ("id", "post_id", "filename", "original_name", "mime_type", "size", "storage_key", "provider", "width", "height", "alt", "position", "blurhash", "waveform", "poster_key", "summary", "chars", "media_kind", "created_at", "updated_at") VALUES('med_01km8dj0yhfq895qr99xknnzc2', 'pst_01km8dj1fefq895qrpb55gzyhx', 'med_01km8dj0yhfq895qr99xknnzc2.svg', 'desk-before.svg', 'image/svg+xml', 1110, 'media/med_01km8dj0yhfq895qr99xknnzc2.svg', 'r2', 1200, 900, NULL, 'a0', NULL, NULL, NULL, NULL, NULL, 'image', 1774104151, 1774104151);
INSERT INTO "media" ("id", "post_id", "filename", "original_name", "mime_type", "size", "storage_key", "provider", "width", "height", "alt", "position", "blurhash", "waveform", "poster_key", "summary", "chars", "media_kind", "created_at", "updated_at") VALUES('med_01km8dj2vvfq895qsn1y0nsgjf', 'pst_01km8dj3a0fq895qsykz14qxqk', 'med_01km8dj2vvfq895qsn1y0nsgjf.svg', 'desk-after.svg', 'image/svg+xml', 1108, 'media/med_01km8dj2vvfq895qsn1y0nsgjf.svg', 'r2', 1200, 900, NULL, 'a0', NULL, NULL, NULL, NULL, NULL, 'image', 1774104153, 1774104153);
INSERT INTO "media" ("id", "post_id", "filename", "original_name", "mime_type", "size", "storage_key", "provider", "width", "height", "alt", "position", "blurhash", "waveform", "poster_key", "summary", "chars", "media_kind", "created_at", "updated_at") VALUES('med_01km8djb0qfq895qzwdjsbw3af', 'pst_01km8djbczfq895r0118372ajb', 'med_01km8djb0qfq895qzwdjsbw3af.svg', 'rainy-crosswalk.svg', 'image/svg+xml', 1074, 'media/med_01km8djb0qfq895qzwdjsbw3af.svg', 'r2', 1200, 900, NULL, 'a0', NULL, NULL, NULL, NULL, NULL, 'image', 1774104161, 1774104161);
INSERT INTO "media" ("id", "post_id", "filename", "original_name", "mime_type", "size", "storage_key", "provider", "width", "height", "alt", "position", "blurhash", "waveform", "poster_key", "summary", "chars", "media_kind", "created_at", "updated_at") VALUES('med_01km8djcmwfq895r16jdmg1v9h', 'pst_01km8djd28fq895r1awr8rm5v4', 'med_01km8djcmwfq895r16jdmg1v9h.svg', 'tomato-soup.svg', 'image/svg+xml', 962, 'media/med_01km8djcmwfq895r16jdmg1v9h.svg', 'r2', 1200, 900, NULL, 'a0', NULL, NULL, NULL, NULL, NULL, 'image', 1774104163, 1774104163);
INSERT INTO "media" ("id", "post_id", "filename", "original_name", "mime_type", "size", "storage_key", "provider", "width", "height", "alt", "position", "blurhash", "waveform", "poster_key", "summary", "chars", "media_kind", "created_at", "updated_at") VALUES('med_01km8djpeffq895r8xyg2ap5qa', 'pst_01km8djpvcfq895r93m6feb6dt', 'med_01km8djpeffq895r8xyg2ap5qa.svg', 'notebook-pages.svg', 'image/svg+xml', 906, 'media/med_01km8djpeffq895r8xyg2ap5qa.svg', 'r2', 1200, 900, NULL, 'a0', NULL, NULL, NULL, NULL, NULL, 'image', 1774104173, 1774104173);

