/**
 * Migration Integrity Tests
 *
 * Ensures every migration SQL file is tracked in the Drizzle journal.
 * Hand-written migrations bypass drizzle-kit and won't have journal entries,
 * which breaks `drizzle-kit generate` for future schema changes.
 *
 * Fix: always run `mise run db-generate` instead of writing SQL by hand.
 */

import { describe, it, expect } from "vitest";
import Database from "better-sqlite3";
import { readdirSync, readFileSync } from "fs";
import { resolve } from "path";

const MIGRATIONS_DIR = resolve(import.meta.dirname, "../migrations");
const JOURNAL_PATH = resolve(MIGRATIONS_DIR, "meta/_journal.json");

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

function readJournal(): Journal {
  return JSON.parse(readFileSync(JOURNAL_PATH, "utf-8"));
}

function listMigrationFiles(): string[] {
  return readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort();
}

function applyMigration(
  sqlite: Database.Database,
  filename: string,
  options?: { skipFts?: boolean },
) {
  const migration = readFileSync(resolve(MIGRATIONS_DIR, filename), "utf-8");
  for (const sql of migration.split("--> statement-breakpoint")) {
    const trimmed = sql.trim();
    if (!trimmed) continue;
    if (options?.skipFts && trimmed.includes("post_fts")) continue;
    sqlite.exec(trimmed);
  }
}

describe("migration integrity", () => {
  it("every SQL file has a corresponding journal entry", () => {
    const journal = readJournal();
    const tags = new Set(journal.entries.map((e) => e.tag));
    const sqlFiles = listMigrationFiles();

    const untracked = sqlFiles
      .map((f) => f.replace(".sql", ""))
      .filter((tag) => !tags.has(tag));

    expect(
      untracked,
      [
        "These migration files are not tracked in meta/_journal.json.",
        "This usually means they were hand-written instead of generated with `mise run db-generate`.",
        "Fix: update src/db/schema.ts first, then run `mise run db-generate`.",
        `Untracked files: ${untracked.map((t) => `${t}.sql`).join(", ")}`,
      ].join("\n"),
    ).toEqual([]);
  });

  it("every journal entry has a corresponding SQL file", () => {
    const journal = readJournal();
    const sqlFiles = new Set(
      listMigrationFiles().map((f) => f.replace(".sql", "")),
    );

    const missing = journal.entries
      .map((e) => e.tag)
      .filter((tag) => !sqlFiles.has(tag));

    expect(
      missing,
      [
        "These journal entries have no matching SQL file.",
        `Missing files: ${missing.map((t) => `${t}.sql`).join(", ")}`,
      ].join("\n"),
    ).toEqual([]);
  });

  it("journal entries have sequential idx values", () => {
    const journal = readJournal();
    for (let i = 0; i < journal.entries.length; i++) {
      const entry = journal.entries[i];
      if (entry) expect(entry.idx).toBe(i);
    }
  });

  it("latest migration has a snapshot file", () => {
    const journal = readJournal();
    const lastEntry = journal.entries[journal.entries.length - 1];
    if (!lastEntry) return;

    const prefix = lastEntry.tag.split("_")[0];
    const snapshotPath = resolve(
      MIGRATIONS_DIR,
      `meta/${prefix}_snapshot.json`,
    );

    let exists = false;
    try {
      readFileSync(snapshotPath);
      exists = true;
    } catch {
      // file doesn't exist
    }

    expect(
      exists,
      [
        `Missing snapshot for latest migration: meta/${prefix}_snapshot.json`,
        "This means the migration was not generated by drizzle-kit.",
        "Fix: run `mise run db-generate` to regenerate it properly.",
      ].join("\n"),
    ).toBe(true);
  });

  it("backfills legacy system nav rows before enforcing system_key constraints", () => {
    const sqlite = new Database(":memory:");
    sqlite.pragma("foreign_keys = ON");

    for (const filename of [
      "0000_baseline.sql",
      "0002_closed_blockbuster.sql",
      "0003_mysterious_wind_dancer.sql",
      "0004_workable_true_believers.sql",
    ]) {
      applyMigration(sqlite, filename, { skipFts: true });
    }

    sqlite.exec(`
      INSERT INTO nav_item (id, type, label, url, position, created_at, updated_at) VALUES
        ('nav-collections', 'system', 'Collections', '/c', 'a0', 1, 1),
        ('nav-archive', 'system', 'Archive', '/archive', 'a1', 1, 1),
        ('nav-rss', 'system', 'RSS', '/feed', 'a2', 1, 1),
        ('nav-dashboard', 'system', 'Dashboard', '/dash', 'a3', 1, 1),
        ('nav-duplicate-settings', 'system', 'Settings', '/settings', 'a4', 1, 1),
        ('nav-legacy-custom', 'system', 'Legacy', '/legacy', 'a5', 1, 1);
    `);

    applyMigration(sqlite, "0004z_nav_item_system_key_backfill.sql");
    applyMigration(sqlite, "0005_happy_slyde.sql");

    const rows = sqlite
      .prepare(
        "SELECT id, type, system_key AS systemKey, label, url FROM nav_item ORDER BY position",
      )
      .all();

    expect(rows).toEqual([
      {
        id: "nav-collections",
        type: "system",
        systemKey: "collections",
        label: "Collections",
        url: "/c",
      },
      {
        id: "nav-archive",
        type: "system",
        systemKey: "archive",
        label: "Archive",
        url: "/archive",
      },
      {
        id: "nav-rss",
        type: "system",
        systemKey: "rss",
        label: "RSS",
        url: "/feed",
      },
      {
        id: "nav-dashboard",
        type: "system",
        systemKey: "settings",
        label: "Settings",
        url: "/settings",
      },
      {
        id: "nav-duplicate-settings",
        type: "link",
        systemKey: null,
        label: "Settings",
        url: "/settings",
      },
      {
        id: "nav-legacy-custom",
        type: "link",
        systemKey: null,
        label: "Legacy",
        url: "/legacy",
      },
    ]);
  });
});
