/**
 * Migration Integrity Tests
 *
 * Ensures every migration SQL file is tracked in the Drizzle journal.
 * Hand-written migrations bypass drizzle-kit and won't have journal entries,
 * which breaks `drizzle-kit generate` for future schema changes.
 *
 * Fix: always run `mise run db-generate` instead of writing SQL by hand.
 */

import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync } from "fs";
import { resolve } from "path";

const MIGRATIONS_DIR = resolve(import.meta.dirname, "../migrations");
const JOURNAL_PATH = resolve(MIGRATIONS_DIR, "meta/_journal.json");

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

function readJournal(): Journal {
  return JSON.parse(readFileSync(JOURNAL_PATH, "utf-8"));
}

function listMigrationFiles(): string[] {
  return readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort();
}

describe("migration integrity", () => {
  it("every SQL file has a corresponding journal entry", () => {
    const journal = readJournal();
    const tags = new Set(journal.entries.map((e) => e.tag));
    const sqlFiles = listMigrationFiles();

    const untracked = sqlFiles
      .map((f) => f.replace(".sql", ""))
      .filter((tag) => !tags.has(tag));

    expect(
      untracked,
      [
        "These migration files are not tracked in meta/_journal.json.",
        "This usually means they were hand-written instead of generated with `mise run db-generate`.",
        "Fix: update src/db/schema.ts first, then run `mise run db-generate`.",
        `Untracked files: ${untracked.map((t) => `${t}.sql`).join(", ")}`,
      ].join("\n"),
    ).toEqual([]);
  });

  it("every journal entry has a corresponding SQL file", () => {
    const journal = readJournal();
    const sqlFiles = new Set(
      listMigrationFiles().map((f) => f.replace(".sql", "")),
    );

    const missing = journal.entries
      .map((e) => e.tag)
      .filter((tag) => !sqlFiles.has(tag));

    expect(
      missing,
      [
        "These journal entries have no matching SQL file.",
        `Missing files: ${missing.map((t) => `${t}.sql`).join(", ")}`,
      ].join("\n"),
    ).toEqual([]);
  });

  it("journal entries have sequential idx values", () => {
    const journal = readJournal();
    for (let i = 0; i < journal.entries.length; i++) {
      const entry = journal.entries[i];
      if (entry) expect(entry.idx).toBe(i);
    }
  });

  it("latest migration has a snapshot file", () => {
    const journal = readJournal();
    const lastEntry = journal.entries[journal.entries.length - 1];
    if (!lastEntry) return;

    const prefix = lastEntry.tag.split("_")[0];
    const snapshotPath = resolve(
      MIGRATIONS_DIR,
      `meta/${prefix}_snapshot.json`,
    );

    let exists = false;
    try {
      readFileSync(snapshotPath);
      exists = true;
    } catch {
      // file doesn't exist
    }

    expect(
      exists,
      [
        `Missing snapshot for latest migration: meta/${prefix}_snapshot.json`,
        "This means the migration was not generated by drizzle-kit.",
        "Fix: run `mise run db-generate` to regenerate it properly.",
      ].join("\n"),
    ).toBe(true);
  });
});
