name: Deploy demo-source

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to demo-source.jant.me
    uses: ./.github/workflows/deploy.yml
    with:
      working_directory: sites/demo-source
      github_environment: demo-source
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
