name: Deploy content-lab

on:
  push:
    branches:
      - main
    paths:
      - "packages/core/**"
      - "sites/content-lab/**"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/deploy-content-lab.yml"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to content-lab.jant.me
    uses: ./.github/workflows/deploy.yml
    with:
      working_directory: sites/content-lab
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
